# Generated by Django 5.0.7 on 2024-08-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_otp_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('financial_institution', 'Financial Institution'), ('farmer', 'Farmer'), ('buyer', 'Buyer'), ('government_agency', 'Government Agency'), ('logistics_provider', 'Logistics Provider')], max_length=30),
        ),
    ]
